# Generated by Django 3.2.7 on 2021-09-30 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Swipe_app', '0002_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like_dislike',
        ),
    ]
