# Generated by Django 3.2.7 on 2021-09-30 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Swipe_app', '0003_delete_like_dislike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like_dislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(blank=True, max_length=50)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='Swipe_app.phonemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='Swipe_app.phonemodel')),
            ],
        ),
    ]
